# build-sprites.ps1
# Reads every .png from ..\assets\sprites\, base64-encodes it, and writes sprites.js
# Run this whenever you add new sprites to the sprites folder:
#   cd tools
#   .\build-sprites.ps1

$spritesDir = Join-Path $PSScriptRoot "..\assets\sprites"
$outFile    = Join-Path $PSScriptRoot "sprites.js"
$pattern    = [regex]'^\(([^)]+)\)([^_]+)_.+\.png$'

$files = Get-ChildItem -Path $spritesDir -Filter '*.png' | Sort-Object Name
$entries = [System.Collections.Generic.List[string]]::new()

foreach ($f in $files) {
    $m = $pattern.Match($f.Name)
    if (-not $m.Success) { continue }
    $qualifier = $m.Groups[1].Value
    $itemId    = $m.Groups[2].Value
    $bytes     = [System.IO.File]::ReadAllBytes($f.FullName)
    $b64       = [System.Convert]::ToBase64String($bytes)
    $key       = "${qualifier}:${itemId}"
    $keyJson   = '"' + $key.Replace('\','\\').Replace('"','\"') + '"'
    $entries.Add("  ${keyJson}: `"data:image/png;base64,${b64}`"")
}

$sb = [System.Text.StringBuilder]::new()
$null = $sb.AppendLine('// AUTO-GENERATED by build-sprites.ps1 — do not edit by hand.')
$null = $sb.AppendLine("// $($entries.Count) sprites embedded.")
$null = $sb.AppendLine('window.GMDF_SPRITES = {')
for ($i = 0; $i -lt $entries.Count; $i++) {
    if ($i -lt $entries.Count - 1) { $null = $sb.AppendLine($entries[$i] + ',') }
    else                            { $null = $sb.AppendLine($entries[$i]) }
}
$null = $sb.AppendLine('};')

[System.IO.File]::WriteAllText($outFile, $sb.ToString(), [System.Text.UTF8Encoding]::new($false))
Write-Host "Done: $($entries.Count) sprites -> $outFile"
