#!/usr/bin/env python3
"""
build-sprites.py
Reads every .png from ../assets/sprites/, base64-encodes it, and writes
sprites.js next to this script.

Run whenever you add new sprites:
    cd tools
    python build-sprites.py
"""

import os, base64, json, re

SCRIPT_DIR  = os.path.dirname(os.path.abspath(__file__))
SPRITES_DIR = os.path.join(SCRIPT_DIR, '..', 'assets', 'sprites')
OUT         = os.path.join(SCRIPT_DIR, 'sprites.js')

FNAME_RE = re.compile(r'^\(([^)]+)\)([^_]+)_.+\.png$', re.IGNORECASE)

entries, skipped = {}, []

for fname in sorted(os.listdir(SPRITES_DIR)):
    if not fname.lower().endswith('.png'):
        continue
    m = FNAME_RE.match(fname)
    if not m:
        skipped.append(fname)
        continue
    qualifier, item_id = m.group(1), m.group(2)
    with open(os.path.join(SPRITES_DIR, fname), 'rb') as f:
        b64 = base64.b64encode(f.read()).decode('ascii')
    entries[f"{qualifier}:{item_id}"] = f"data:image/png;base64,{b64}"

lines = [
    '// AUTO-GENERATED by build-sprites.py — do not edit by hand.',
    f'// {len(entries)} sprites embedded.',
    'window.GMDF_SPRITES = {',
]
items = list(entries.items())
for i, (k, v) in enumerate(items):
    comma = ',' if i < len(items) - 1 else ''
    lines.append(f'  {json.dumps(k)}: {json.dumps(v)}{comma}')
lines.append('};')

with open(OUT, 'w', encoding='utf-8') as f:
    f.write('\n'.join(lines) + '\n')

print(f"✓ Wrote {len(entries)} sprites → {OUT}")
if skipped:
    print(f"  Skipped {len(skipped)}: {skipped[:3]}{'…' if len(skipped)>3 else ''}")
